services:
  - type: web
    name: sem-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python sem_server.py
    envVars:
      - key: PORT
        value: 8080
